# https://fte.triptohell.info/moodles/linux_amd64/fteqw64

name: Weekly Demos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache Quake resources
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            fteqw
            id1/pak0.pak
            qw/maps/maphub_v1.bsp
            qw/progs/end2.mdl
            qw/progs/end3.mdl
            qw/progs/end4.mdl
            qw/progs/spawn.mdl
            qw/progs/v_coil.mdl
            qw/progs/v_spike.mdl
            qw/progs/vwplayer.mdl
            qw/progs/w_axe.mdl
            qw/progs/w_coil.mdl
            qw/progs/w_light.mdl
            qw/progs/w_nail2.mdl
            qw/progs/w_nail.mdl
            qw/progs/w_rock2.mdl
            qw/progs/w_rock.mdl
            qw/progs/w_shot2.mdl
            qw/progs/w_shot.mdl
          key: static-key-2

      - name: Install packages
        run: sudo apt-get -qq install expect unzip lhasa

      - name: Fetch dependencies
        run: |
          curl -s -o fteqw https://fte.triptohell.info/moodles/linux_amd64/fteqw64
          chmod 755 fteqw

          # Alternative:
          # https://archive.org/download/msdos_Quake106_shareware/msdos_Quake106_shareware.zip/ID1%2FPAK0.PAK
          curl -s -O https://www.quaddicted.com/files/idgames2/idstuff/quake/quake106.zip
          unzip quake106.zip resource.1
          lha x resource.1 id1/pak0.pak

          mkdir -p qw/maps
          curl -s -o qw/maps/maphub_v1.bsp http://maps.quakeworld.nu/maphub_v1.bsp

          curl -s -o vwep.zip -L https://gfx.quakeworld.nu/download/238/trickles-vwep-package/
          unzip vwep.zip "qw/progs/*"

          curl -s -o vwplayer.zip https://gfx.quakeworld.nu/download/312/vwplayermdl-vwep-prerequisity/
          unzip -d qw/progs vwplayer.zip
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Fetch demos
        run: expect -d ./fetch-demos

      - name: Filter unfinished matches
        run: |
          curl -O https://raw.githubusercontent.com/qw-ctf/ktx-stats/master/ktx-stats.py

          for demo in qw/demos/*.mvd; do
            python ktx-stats.py "${demo}"
            
            duration=$(jq '.duration' "${demo/mvd/json}")
            if ! ((${duration} % 60)); then
              gzip -9 "${demo}"
              mv "${demo}.gz" weeklies
            else
              echo "${duration}" > ignored/$(basename $demo).ignored
            fi
          done

      - name: Push changes
        id: push-changes
        run: |
          git config --global user.name 'Demo Fetcher'
          git config --global user.email dsvensson@users.noreply.github.com'
          if git commit -am "Weekly demos"; then
            HASH=$(git rev-parse --verify HEAD)
            git push -f "${HASH}:refs/heads/weekly-demos"
            echo "::set-output name=commithash::$HASH"
          fi

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Weekly Demos',
              owner,
              repo,
              head: 'weekly-demos',
              base: 'main',
              body: [
                'This PR is auto-generated by CI pipeline'
              ].join('\n')
            });
        if: steps.push-changes.outputs.commithash != ''

          
