# https://fte.triptohell.info/moodles/linux_amd64/fteqw64

name: Weekly Demos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache FTEQW Client
        uses: actions/cache@v3
        id: cache-fteqw
        with:
          path: /usr/bin/fteqw
          key: fteqw

      - name: Fetch FTEQW
        run: |
          curl -q -o fteqw https://fte.triptohell.info/moodles/linux_amd64/fteqw64
          chmod 755 fteqw
          sudo mv fteqw /usr/bin/

      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: bleh
        run: ls -lR
