# https://fte.triptohell.info/moodles/linux_amd64/fteqw64

name: Weekly Demos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: bleh
        run: ls -lR
